### ISSUE TITLE
Install issues on Mac

### ISSUE THREAD

**Issue by jwreep** [wtbarnes/hissw#36]
Working on MacOS Sonoma 14.2.

I've tried installing, and can't get the pytest to run.  Likely a user error, but I'm trying to follow the install directions . . . 

```
(base) reep@Jeffreys-iMac hissw % pytest --version
pytest 7.4.0
```

Installed with pip:
```
(base) reep@Jeffreys-iMac hissw % pwd
/Users/reep/anaconda3/lib/python3.11/site-packages/hissw
(base) reep@Jeffreys-iMac hissw % ls
__init__.py	environment.py	read_config.py	tests
__pycache__	filters.py	templates	util.py
```

The `$HOME/.hissw` was not created automatically (directions sound like it should be?).  I created it myself:
```
(base) reep@atrcw8 .hissw % ls
hisswrc
(base) reep@atrcw8 .hissw % pwd
/Users/reep/.hissw
```
Along with the `hisswrc` file:
```
[hissw]
ssw_home=/Users/reep/ssw/
idl_home=/Applications/harris/idl89/
```

And then run `pytest` in the directory `/Users/reep/anaconda3/lib/python3.11/site-packages/hissw`, which returns 23 errors, all of which say: `E       fixture 'idl_home' not found`.  

Manually trying to add `idl_home`:
```
(base) reep@Jeffreys-iMac hissw % pytest --ssw_home="/Users/reep/ssw/" --idl_home="/Applications/harris/idl89/"
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --ssw_home=/Users/reep/ssw/ --idl_home=/Applications/harris/idl89/
  inifile: None
  rootdir: /Users/reep/anaconda3/lib/python3.11/site-packages/hissw
```

I'm lost.  What have I done wrong here?

**Comment by wtbarnes** [comment]
To run pytest, you'll need to clone the repo via GitHub. Generally speaking, if you're installing from PyPI, the thinking is you're probably not too interested in running the tests. This seems to not be clear from the README/docs though so apologies for confusion. 

The error you're seeing is because pytest can't see any of the custom command line arguments that hissw implements because the file that specifies these (`conftest.py`) is not included in the installed package. This is by design because this file is not needed for actually using the package, only for running the tests. 

Rather than running the tests, I would have a look in the examples in the docs and check whether one of them works for you. 

Regarding the configfile, it's actually not created automatically. We could change this, but the problem is that it's hard to guess where a user might have idl installed so we may as well force them create the file themselves (or alternatively just specify those paths when setting up the environment).

**Comment by jwreep** [comment]
Thanks, Will.  It works fine.
