### ISSUE TITLE
v1.1 Release

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/hissw#7]
Need a new release following nomenclature change (see #6)

**Comment by schonfsj** [comment]
I just tried installing hissw from pip and ran into issues because .environment isn't defined. I'm assuming my encountered error is due to this issue. 

Cloning and installing the repository manually worked fine.

**Comment by wtbarnes** [comment]
@schonfsj What was the issue specifically? Beyond inconsistency with the docs, I don't *think* there should be any issue.

If you're following the docs with the latest release on PyPI, you'd need to replace each occurrence of `Environment` with `ScriptMaker`.

Either way, glad it works!

**Comment by schonfsj** [comment]
@wtbarnes Yeah, `ScriptMaker` being replaced with `Environment` was exactly the problem.

I actually can't get the functionality to work, but that's because I'm running a weird hybrid system with IDL running in windows and python running in a WSL linux environment. So it's a compatibility problem of my own creation.

**Comment by wtbarnes** [comment]
@schonfsj I'd be interested in trying to get this to work on Windows, but don't have a machine to test on. If you make any headway, please let me know. I'm happy to incorporate any changes into hissw to get things working on Windows.

**Comment by wtbarnes** [comment]
Version 1.1 is now available on PyPI! @schonfsj I'm going to close this issue and move your Windows compatibility problem to a separate issue.
